### ISSUE TITLE
服务器状态查看遍历到光驱会崩溃

### ISSUE THREAD

**Issue by WhyPilotXia** [cscs181/QQ-GitHub-Bot#18]
data_source.py中函数
```python
def disk_usage():
	disk_parts = psutil.disk_partitions()
	for d in disk_parts:
		return {d.mountpoint: psutil.disk_usage(d.mountpoint)}
```
上面是我改完之后，原函数运行报错，因为遍历到最后一个 光驱会说无法访问，然后崩溃

**Comment by yanyongyu** [comment]
你这样就没法返回所有disk的空间了，可能可以用whitelisk blacklist之类的方法来配置

**Comment by WhyPilotXia** [comment]
嗷嗷




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月12日(星期五) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: "WHEN THREAD ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cscs181/QQ-GitHub-Bot] 服务器状态查看遍历到光驱会崩溃 (Issue #18)





 
你这样就没法返回所有disk的空间了，可能可以用whitelisk blacklist之类的方法来配置

**Comment by WhyPilotXia** [comment]
报错信息 （没法发图）
08-12 20:53:36 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_status, type=notice, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\__init__.py", line 40, in server_status
    disk_usage=disk_usage(),
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\data_source.py", line 34, in disk_usage
    return {d.mountpoint: psutil.disk_usage(d.mountpoint) for d in disk_parts}
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\data_source.py", line 34, in <dictcomp>
    return {d.mountpoint: psutil.disk_usage(d.mountpoint) for d in disk_parts}
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\__init__.py", line 2000, in disk_usage
    return _psplatform.disk_usage(path)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\_pswindows.py", line 274, in disk_usage
    total, free = cext.disk_usage(path)
PermissionError: [WinError 21] 设备未就绪。: 'E'
08-12 20:53:36 [DEBUG] nonebot | Stop event propagation

**Comment by WhyPilotXia** [comment]
报错（发不了图）：
`08-12 20:53:36 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_status, type=notice, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "A:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\__init__.py", line 40, in server_status
    disk_usage=disk_usage(),
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\data_source.py", line 34, in disk_usage
    return {d.mountpoint: psutil.disk_usage(d.mountpoint) for d in disk_parts}
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_status\data_source.py", line 34, in <dictcomp>
    return {d.mountpoint: psutil.disk_usage(d.mountpoint) for d in disk_parts}
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\__init__.py", line 2000, in disk_usage
    return _psplatform.disk_usage(path)
  File "A:\Users\27432\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psutil\_pswindows.py", line 274, in disk_usage
    total, free = cext.disk_usage(path)
PermissionError: [WinError 21] 设备未就绪。: 'E'
08-12 20:53:36 [DEBUG] nonebot | Stop event propagation
`

**Comment by WhyPilotXia** [comment]
![image](https://user-images.githubusercontent.com/86997355/184360491-c1fd9a52-edca-4082-b854-d5843e99d1b5.png)

**Comment by yanyongyu** [comment]
在 https://github.com/cscs181/QQ-GitHub-Bot/commit/9075dbb07099a309d9d2a30bb79ef68d27800806 中对报错进行了处理，在下个版本中发布。

**Comment by WhyPilotXia** [comment]
感谢小哥哥!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月13日(周六) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cscs181/QQ-GitHub-Bot] 服务器状态查看遍历到光驱会崩溃 (Issue #18)




 
在 9075dbb 中对报错进行了处理，在下个版本中发布。
