### ISSUE TITLE
tortoise.exceptions.OperationalError: 关系 "user" 不存在

### ISSUE THREAD

**Issue by kitUIN** [cscs181/QQ-GitHub-Bot#48]
俩个数据库均已配置好,成功连上了.
bot正常跑起来了,使用`/auth` 跳转到 `github` 再跳转回来的时候报错

```
08-08 01:49:07 [INFO] uvicorn | 127.0.0.1:43930 - "GET /github/auth?code=ea025bbac5e9efd12693&state=65fddb1a2e164f71b0e679acc7e184c0 HTTP/1.0" 500

08-08 01:49:07 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 143, in execute_query
    rows = await connection.fetch(*params)
  File "/bot/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 620, in fetch
    return await self._execute(
  File "/bot/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/bot/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/bot/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/bot/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
    return await waiter
asyncpg.exceptions.UndefinedTableError: 关系 "user" 不存在

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bot/bot.py", line 39, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/bot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/bot/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/bot/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 284, in __call__
    await super().__call__(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/bot/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/bot/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/bot/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/bot/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/bot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/bot/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/bot/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/bot/src/plugins/github/apis/auth.py", line 51, in auth
    await delete_state_data(state)
  File "/bot/src/plugins/github/libs/auth.py", line 45, in create_auth_user
    return await create_or_update_user(info, access_token=access_token)
  File "/bot/src/plugins/github/libs/platform/user_crud.py", line 41, in create_or_update_user
    user, _ = await User.update_or_create(
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/models.py", line 1105, in update_or_create
    instance = await cls.select_for_update().using_db(connection).get_or_none(**kwargs)
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "/bot/.venv/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 84, in _translate_exceptions
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: 关系 "user" 不存在

```
![image](https://github.com/cscs181/QQ-GitHub-Bot/assets/68675068/9b614e42-3700-4bf4-bd02-42c117d86091)
数据库里什么都没有,是不是需要什么初始化步骤?

**Comment by kitUIN** [comment]
刚看到有[prestart.sh](https://github.com/cscs181/QQ-GitHub-Bot/blob/master/prestart.sh) 闹弹了
